//
// Created by Francesco Ferreri (Namex) on 17/03/25.
//

#ifndef SEAFLOWS_H
#define SEAFLOWS_H
#define SEAFLOWS_VERSION_MAJOR 1
#define SEAFLOWS_VERSION_MINOR 0
#define SEAFLOWS_VERSION_PATCH 0
#define SEAFLOWS_VERSION_STRING "1.0.0"
#define SEAFLOWS_LISTENER_PORT 6343


#endif //SEAFLOWS_H
